---
title: "Make figures for Spectral Bridges Paper"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


## Plotting balls

```{r setup, include=FALSE}
#| echo: false 
#| file: setup-figs.R
```

## Plotting balls

```{r plot-balls, warning=FALSE, message=FALSE}
plot_balls(a = center[1], b = center[2], c = mu2[1], d = mu2[2])
```


## Plotting bridge

```{r, warning=FALSE, message=FALSE}
plot_bridge(a = center[1], b = center[2], c = mu2[1], d = mu2[2])
```

## Spectral bridges on iris data

```{r}
data(iris)
pca <- prcomp(iris[, 1:4], scale. = TRUE)
pca_data <- as.data.frame(pca$x)
X <- pca_data[, 1:2]
colnames(X) <- c("PC1", "PC2")
set.seed(123)
n_nodes <- 20
n <- nrow(X)
kmeans_result <- KMeans_rcpp(X, clusters = n_nodes, num_init = 3, max_iters = 30, initializer = 'kmeans++')
kmeans_centers <- as.matrix(kmeans_result$centroids)
kmeans_labels <- as.matrix(kmeans_result$clusters)
kmeans_size <- kmeans_result$obs_per_cluster
kmeans_Iw <- kmeans_result$WCSS_per_cluster
affinity <- outer(1:n_nodes, 1:n_nodes, Vectorize(function(k, l) {
  if (k == l) 0 else {
    distkl2 <- sum((kmeans_centers[l, ] - kmeans_centers[k, ])^2)
    alphai <- c(pmax(0, (kmeans_centers[l, ] - kmeans_centers[k, ]) %*%
      t(X[kmeans_labels == k, ] - matrix(kmeans_centers[k, ], nrow = sum(kmeans_labels == k), ncol = 2, byrow = TRUE))) / distkl2,
      pmax(0, (kmeans_centers[k, ] - kmeans_centers[l, ]) %*%
        t(X[kmeans_labels == l, ] - matrix(kmeans_centers[l, ], nrow = sum(kmeans_labels == l), ncol = 2, byrow = TRUE))) / distkl2)
    sqrt(sum(alphai^2) / (kmeans_size[k] + kmeans_size[l]))
  }
}))
centroids <- as.data.frame(kmeans_result$centroids)
colnames(centroids) <- c("PC1", "PC2")
voronoi <- deldir(centroids$PC1, centroids$PC2)
tiles <- tile.list(voronoi)
voronoi_df <- do.call(rbind, lapply(1:length(tiles), function(i) {
  tile <- tiles[[i]]
  data.frame(x = tile$x, y = tile$y, id = i)
}))
p <- ggplot() +
  geom_point(data = X, aes(x = PC1, y = PC2, color = as.factor(kmeans_result$clusters), alpha = 0.4)) +
  geom_polygon(data = voronoi_df, aes(x = x, y = y, group = id), color = "black", alpha = 0.2, fill = "white") +
  geom_point(data = centroids, aes(x = PC1, y = PC2), color = "red", size = 5) +
  theme_minimal() +
  theme(panel.grid = element_blank(), legend.position = "none",
        axis.title = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), axis.line = element_blank())
#pdf("spectral-bridges-iris-1.pdf")
print(p)
#dev.off()
```

```{r}
affinity_lines <- data.frame(
  x = rep(centroids$PC1, each = n_nodes),
  y = rep(centroids$PC2, each = n_nodes),
  xend = rep(centroids$PC1, times = n_nodes),
  yend = rep(centroids$PC2, times = n_nodes),
  weight = as.vector(affinity)
)
affinity_lines <- subset(affinity_lines, weight > 0.1)
p <- ggplot() +
  geom_point(data = X, aes(x = PC1, y = PC2, color = as.factor(kmeans_result$clusters), alpha = 0.4)) +
  geom_polygon(data = voronoi_df, aes(x = x, y = y, group = id), color = "black", alpha = 0.2, fill = "white") +
  geom_segment(data = affinity_lines, aes(x = x, y = y, xend = xend, yend = yend, size = weight), color = "blue") +
  geom_point(data = centroids, aes(x = PC1, y = PC2), color = "red", size = 5) +
  scale_size_continuous(range = c(0.5, 2)) +
  theme_minimal() +
  theme(panel.grid = element_blank(), legend.position = "none",
        axis.title = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), axis.line = element_blank())
#pdf("spectral-bridges-iris-2.pdf")
print(p)
#dev.off()
```

```{r}
affinity.old <- affinity
affinity[affinity < 0.1] <- 0
transform <- "exp"
M <- 1e3
if (transform == "exp") {
  gamma <- log(M) / diff(quantile(affinity.old, c(0.1, 0.9)))
  affinity.old <- exp(gamma * (affinity.old - 0.5 * max(affinity.old)))
}
D_inv_sqrt <- 1 / sqrt(rowSums(affinity.old))
L <- diag(n_nodes) - t(affinity.old * D_inv_sqrt) * D_inv_sqrt
eigen.res <- eigen(-L, symmetric = TRUE)
n_classes <- 3
eigvecs <- eigen.res$vectors[, 1:n_classes]
eigvecs <- eigvecs / sqrt(rowSums(eigvecs ^ 2))
labels <- kmeans(eigvecs, nstart = 20, centers = n_classes)$cluster
clusters <- labels[kmeans_labels]
centroids$label <- as.factor(labels)
p <- ggplot() +
  geom_point(data = X, aes(x = PC1, y = PC2, color = as.factor(clusters), alpha = 0.4)) +
  geom_polygon(data = voronoi_df, aes(x = x, y = y, group = id, fill = as.factor(labels[id])), color = "black", alpha = 0.2) +
  geom_point(data = centroids, aes(x = PC1, y = PC2), color = as.factor(labels+1), size = 5) +
  theme_minimal() +
  theme(panel.grid = element_blank(), legend.position = "none",
        axis.title = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), axis.line = element_blank())
#pdf("spectral-bridges-iris-3-4.pdf")
print(p)
#dev.off()
```

## Exploration of cancer data

```{r, message=FALSE, warning=FALSE}
X <- read.csv("cancer.csv", header = FALSE)
y <- X[, 31]
X <- X[, -31]
pca_result <- prcomp(X, scale. = TRUE)
pca_data <- as.data.frame(pca_result$x[, 1:4])
colnames(pca_data) <- c("PC1", "PC2", "PC3", "PC4")
pca_data$Group <- as.factor(y)
cancer_plot <- ggpairs(pca_data, columns = 1:4, aes(color = Group, alpha = 0.5)) +
  theme_minimal() +
  labs(title = "ACP avec les quatre premières composantes principales",
       subtitle = "Coloré selon le vecteur y")
print(cancer_plot)
```

```{r}
res <- spectral_bridges(X, n_classes = 2, n_cells = 6)
table(y, res$clustering)
ari <- adjustedRandIndex(y, res$clustering)
print(paste("Adjusted Rand Index (ARI):", ari))
```

## Illustrating circles

```{r}
# Génération d'un jeu de données simulé si circles.csv absent
if (!file.exists("circles.csv")) {
  set.seed(123)
  n <- 400
  t <- runif(n, 0, 2 * pi)
  r <- c(rep(1, n/2), rep(2, n/2))
  x <- r * cos(t) + rnorm(n, 0, 0.1)
  y <- r * sin(t) + rnorm(n, 0, 0.1)
  label <- c(rep(1, n/2), rep(2, n/2))
  write.csv(data.frame(V1 = x, V2 = y, V3 = label), "circles.csv", row.names = FALSE, col.names = FALSE)
}
X <- read.csv("circles.csv", header = FALSE)
y <- X[, 3]
X <- X[, -3]
set.seed(123)
n_nodes <- 60
n <- nrow(X)
kmeans_result <- KMeans_rcpp(X, clusters = n_nodes, num_init = 3, max_iters = 30, initializer = 'kmeans++')
kmeans_centers <- as.matrix(kmeans_result$centroids)
kmeans_labels <- as.matrix(kmeans_result$clusters)
kmeans_size <- kmeans_result$obs_per_cluster
kmeans_Iw <- kmeans_result$WCSS_per_cluster
X.centered <- as.matrix(do.call(rbind, lapply(1:n, function(i) {
  X[i, ] - kmeans_centers[kmeans_labels[i], ]
})))
affinity <- outer(1:n_nodes, 1:n_nodes, Vectorize(function(k, l) {
  if (k == l) return(0)
  else {
    distkl2 <- sum((kmeans_centers[l, ] - kmeans_centers[k, ])^2)
    alphai <- c(pmax(0, (kmeans_centers[l, ] - kmeans_centers[k, ]) %*%
      t(X.centered[kmeans_labels == k, ])) / distkl2,
      pmax(0, (kmeans_centers[k, ] - kmeans_centers[l, ]) %*%
        t(X.centered[kmeans_labels == l, ])) / distkl2)
    return(sqrt(sum(alphai^2) / (kmeans_size[k] + kmeans_size[l])))
  }
}))
centroids <- as.data.frame(kmeans_result$centroids)
colnames(centroids) <- c("V1", "V2")
voronoi <- deldir(centroids$V1, centroids$V2)
voronoi_edges_df <- as.data.frame(voronoi$dirsgs)
p <- ggplot() +
  geom_point(data = X, aes(x = V1, y = V2, color = as.factor(kmeans_result$clusters), alpha = 0.4)) +
  geom_segment(data = voronoi_edges_df, aes(x = x1, y = y1, xend = x2, yend = y2), color = "black") +
  geom_point(data = centroids, aes(x = V1, y = V2), color = "red", size = 5) +
  theme_minimal() +
  theme(panel.grid = element_blank(), legend.position = "none",
        axis.title = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), axis.line = element_blank())
pdf("spectral-bridges-circle-1.pdf")
print(p)
dev.off()
```

```{r}
affinity_lines <- data.frame(
  x = rep(centroids$V1, each = n_nodes),
  y = rep(centroids$V2, each = n_nodes),
  xend = rep(centroids$V1, times = n_nodes),
  yend = rep(centroids$V2, times = n_nodes),
  weight = as.vector(affinity)
)
affinity_lines <- subset(affinity_lines, weight > 0.1)
p <- ggplot() +
  geom_point(data = X, aes(x = V1, y = V2, color = as.factor(kmeans_result$clusters), alpha = 0.4)) +
  geom_segment(data = voronoi_edges_df, aes(x = x1, y = y1, xend = x2, yend = y2), color = "black") +
  geom_segment(data = affinity_lines, aes(x = x, y = y, xend = xend, yend = yend), color = "blue", alpha = 0.4) +
  geom_point(data = centroids, aes(x = V1, y = V2), color = "red", size = 5) +
  scale_size_continuous(range = c(0.5, 2)) +
  theme_minimal() +
  theme(panel.grid = element_blank(), legend.position = "none",
        axis.title = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), axis.line = element_blank())
pdf("spectral-bridges-circle-2.pdf")
print(p)
dev.off()
```

```{r}
tiles <- tile.list(voronoi)
voronoi_df <- do.call(rbind, lapply(1:length(tiles), function(i) {
  tile <- tiles[[i]]
  data.frame(x = tile$x, y = tile$y, id = i)
}))
affinity.old <- affinity
affinity[affinity < 0.1] <- 0
transform <- "exp"
M <- 1e3
if (transform == "exp") {
  gamma <- log(M) / diff(quantile(affinity.old, c(0.1, 0.9)))
  affinity.old <- exp(gamma * (affinity.old - 0.5 * max(affinity.old)))
}
D_inv_sqrt <- 1 / sqrt(rowSums(affinity.old))
L <- diag(n_nodes) - t(affinity.old * D_inv_sqrt) * D_inv_sqrt
eigen.res <- eigen(-L, symmetric = TRUE)
n_classes <- 3
eigvecs <- eigen.res$vectors[, 1:n_classes]
eigvecs <- eigvecs / sqrt(rowSums(eigvecs ^ 2))
labels <- kmeans(eigvecs, nstart = 20, centers = n_classes)$cluster
clusters <- y
p <- ggplot() +
  geom_point(data = X, aes(x = V1, y = V2, color = as.factor(clusters), alpha = 0.4)) +
  geom_polygon(data = voronoi_df, aes(x = x, y = y, group = id, fill = as.factor(labels[id])), color = "black", alpha = 0.2) +
  geom_point(data = centroids, aes(x = V1, y = V2), color = as.factor(labels+1), size = 5) +
  theme_minimal() +
  theme(panel.grid = element_blank(), legend.position = "none",
        axis.title = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), axis.line = element_blank())
pdf("spectral-bridges-circle-3-4.pdf")
print(p)
dev.off()
```
